/**
 * Writes `src/data/flagCodes.ts`: the codes Hata has a flag for, so a country or a subdivision can say whether it has one
 * (`flag` is its address on the CDN, or `null`) without installing Hata, which is 27 MB of flags. The list is made from the
 * installed Hata, and `test/flags.test.ts` fails when it is not the installed Hata's own.
 *
 *   node scripts/hata-codes.ts
 */
import { writeFileSync } from 'node:fs';
import { FLAG_CODES, VERSION } from '@johnmorrisdotca/hata';

const lines = [
  '// Generated by scripts/hata-codes.ts from @johnmorrisdotca/hata. Do not edit by hand.',
  '',
  `/** The Hata version this list is of: ${VERSION}. */`,
  `export const HATA_VERSION = ${JSON.stringify(VERSION)};`,
  '',
  '/** The ISO 3166-1 and 3166-2 codes Hata has a flag for, as Kuni writes them. */',
  `export const FLAG_CODES: readonly string[] = ${JSON.stringify([...FLAG_CODES].join(' '))}.split(' ');`,
  '',
];
writeFileSync(new URL('../src/data/flagCodes.ts', import.meta.url), lines.join('\n'));
console.log(`Wrote ${FLAG_CODES.length} flag codes of Hata ${VERSION}.`);
