/**
 * Writes `src/data/kuniLocal.ts`: the two small tables Kuni 1.2.0 on npm does not have yet, the IOC code of each
 * country and the 31 withdrawn countries of ISO 3166-3 (Wikidata, CC0). They are made from a Kuni checkout that has
 * them (its `dist/`), so the numbers here are Kuni's own, and `test/kuni-local.test.ts` switches this off the day the
 * installed Kuni answers them itself (1.3.0): the file is then deleted and `src/data/kuni.ts` reads Kuni.
 *
 *   KUNI_DIST=/path/to/kuni/dist node scripts/kuni-local-tables.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dist = process.env.KUNI_DIST;
if (!dist) throw new Error('Set KUNI_DIST to the dist/ folder of a Kuni build that has /withdrawn and country().ioc.');
const kuni = await import(join(dist, 'index.js'));
const withdrawn = await import(join(dist, 'withdrawn.js'));

const ioc: Record<string, string> = {};
for (const country of kuni.countries() as { alpha2: string; ioc?: string }[])
  if (country.ioc) ioc[country.alpha2] = country.ioc;

const rows = (withdrawn.withdrawnCountries() as Record<string, unknown>[]).map((one) =>
  JSON.parse(JSON.stringify(one)),
);
const lines = [
  '// Generated by scripts/kuni-local-tables.ts from a Kuni build. Do not edit by hand.',
  "// Kuni's data, which npm's 1.2.0 does not carry yet: Olympic codes and the withdrawn countries of ISO 3166-3,",
  `// from Wikidata (CC0), read on ${withdrawn.WITHDRAWN_READ}. Once Kuni 1.3.0 is installed, delete this file.`,
  '',
  'export interface LocalWithdrawn {',
  '  code: string;',
  '  alpha2: string;',
  '  alpha3?: string;',
  '  numeric?: string;',
  '  name: { en: string; ja: string | null };',
  '  since: string;',
  '  until: string;',
  '  successors: readonly string[];',
  '  reusedBy?: string;',
  '}',
  '',
  `export const WITHDRAWN_READ = ${JSON.stringify(withdrawn.WITHDRAWN_READ)};`,
  '',
  "/** Country alpha-2 code to the International Olympic Committee's three letters. */",
  `export const IOC_CODES: Readonly<Record<string, string>> = ${JSON.stringify(ioc)};`,
  '',
  '/** The 31 entries of ISO 3166-3, in order of their four-letter code. */',
  `export const WITHDRAWN: readonly LocalWithdrawn[] = ${JSON.stringify(rows, null, 1)};`,
  '',
];
writeFileSync(new URL('../src/data/kuniLocal.ts', import.meta.url), lines.join('\n'));
console.log(`Wrote ${Object.keys(ioc).length} IOC codes and ${rows.length} withdrawn countries.`);
